repos:
-   repo: https://github.com/timothycrosley/isort/
    rev: 5.2.0
    hooks:
    - id: isort
      args: ['--silent-overwrite']
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
      args: ['--silent-overwrite']